# Dockerfile.dev para FrontEnd (hot reload)
FROM node:22-alpine

WORKDIR /app

# Copia los archivos de configuración de dependencias desde la carpeta Frontend
COPY Frontend/package*.json ./

# Instala todas las dependencias
RUN npm install

# Copia todo el código fuente del frontend
COPY Frontend/ .

EXPOSE 4200

# Comando estándar para servir una app de Angular en desarrollo
CMD ["npm", "start", "--", "--host", "0.0.0.0", "--disable-host-check"]
