FROM node:22-alpine

WORKDIR /app

# Copia solo package.json y package-lock.json desde la carpeta Servidor
COPY Servidor/package*.json ./

# Instala solo dependencias de producción
RUN npm install --omit=dev

# Copia el código fuente completo desde la carpeta Servidor
COPY Servidor/ .

# Expone el puerto de producción
EXPOSE 3000

# Comando para iniciar la app
CMD ["node", "./bin/www"]
