FROM node:22-alpine

WORKDIR /app

# Copia los archivos de dependencias desde la carpeta Servidor
COPY ./Servidor/package*.json ./

# Instala solo dependencias de producción
RUN npm install --omit=dev

# Copia todo el código fuente de la carpeta Servidor al directorio de trabajo /app
COPY ./Servidor/ .

# Expone el puerto de producción
EXPOSE 3000

# Comando para iniciar la app
CMD ["node", "./bin/www"]
